"""D-Eye Connector Builder Skill.

Scaffolds a new connector against the D-Eye connector contract. Emits
the Python module text (as a string) + a manifest suggestion. Does NOT
write files to disk unless a caller passes an explicit `out_path`.

The generated connector shell always:

- routes network calls through `deye.connectors.base.safe_get`;
- returns an `Envelope` with `trust.untrusted=True`;
- provides a `health()` returning a `HealthReport`;
- exports a `manifests(config)` function so the registry can pick it up.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

_NAME = re.compile(r"^[a-z][a-z0-9_]{1,30}$")


def _render(name: str, capability: str, description: str, license: str) -> str:
    class_name = name.title().replace("_", "") + "Connector"
    return f'''"""{description}"""
from __future__ import annotations

from deye.connectors.base import ConnectorError, safe_get, timed_health
from deye.core.config import Config
from deye.core.provenance import Envelope, Source, Trust
from deye.core.registry import ConnectorManifest, HealthReport


class {class_name}:
    """Generated by deye.skills.connector_builder - customise `run()`."""

    name = "{name}"
    capability = "{capability}"
    is_write = False

    def __init__(self, config: Config | None = None):
        self.config = config or Config()

    def health(self) -> HealthReport:
        return timed_health(
            lambda: HealthReport(self.name, "ok",
                                 "generated {name} connector; review before use"),
        )

    def run(self, request: dict) -> Envelope:
        # TODO: build the target URL from `request` and adjust parsing.
        url = request.get("url") or ""
        if not url:
            raise ConnectorError("{name} needs 'url' in request")
        body, final_url, warnings = safe_get(url, limits=self.config.limits)
        return Envelope(
            content=body.decode("utf-8", errors="replace")[:20000],
            source=Source(url=final_url, connector=self.name,
                          title=f"{name}: {{url}}"),
            trust=Trust(origin="public_web", untrusted=True),
            warnings=warnings,
        )


def manifests(config: Config | None = None) -> list[ConnectorManifest]:
    return [
        ConnectorManifest(
            name="{name}", capability="{capability}", license="{license}",
            requires_credentials=False, cost="free", preference=50,
            origin="public_web",
            factory=lambda: {class_name}(config),
        ),
    ]
'''


def run(*, name: str,
        capability: str = "fetch",
        description: str = "Generated D-Eye connector.",
        license: str = "MIT",
        out_path: str | None = None) -> dict:
    """Return the module text for a new connector shell.

    If *out_path* is provided the module is written to that path.
    Otherwise the caller receives the source as a string.
    """
    if not _NAME.match(name):
        raise ValueError(
            f"invalid connector name {name!r} - must match {_NAME.pattern}"
        )
    if capability not in {"search", "fetch", "feed", "repo.inspect", "extract"}:
        raise ValueError(f"unknown capability {capability!r}")
    module_text = _render(name, capability, description, license)
    written = None
    if out_path:
        p = Path(out_path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(module_text, encoding="utf-8")
        written = str(p)
    return {
        "name": name,
        "capability": capability,
        "module_text": module_text,
        "written_to": written,
        "next_steps": [
            "Customise the `run()` method for your target host + parsing.",
            "Register `manifests(config)` in `deye/app.py::build_registry`.",
            "Add a test file `tests/test_connector_<name>.py` with a "
            "monkeypatched safe_get.",
            "Update `docs/CONNECTOR_GUIDE.md` with the new connector row.",
        ],
    }


from deye.skills import Skill  # noqa: E402

SKILL = Skill(
    name="connector_builder",
    version="1.0.0",
    description=("Scaffold a new connector against the D-Eye connector "
                 "contract: safe_get networking, untrusted Envelope, health "
                 "check, registry manifest."),
    run=run,
    requires_consent=False,
    tags=("scaffold", "connector", "developer"),
)
